# Generated by Django 4.1.7 on 2023-06-17 09:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(default='system')),
                ('updation_date', models.DateTimeField(auto_now=True, null=True)),
                ('updation_by', models.TextField(null=True)),
                ('user_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(default='system')),
                ('updation_date', models.DateTimeField(auto_now=True, null=True)),
                ('updation_by', models.TextField(null=True)),
                ('refresh_token', models.TextField(primary_key=True, serialize=False)),
                ('user_auth', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authapis.userauth')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('status', models.PositiveSmallIntegerField(default=1)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.TextField(default='system')),
                ('updation_date', models.DateTimeField(auto_now=True, null=True)),
                ('updation_by', models.TextField(null=True)),
                ('credential', models.TextField(primary_key=True, serialize=False)),
                ('secret', models.TextField(null=True)),
                ('type', models.PositiveSmallIntegerField()),
                ('last_code_generation_attempt', models.DateTimeField(null=True)),
                ('consecutive_code_generation_attempt_counter', models.PositiveSmallIntegerField()),
                ('last_code_verification_attempt', models.DateTimeField(null=True)),
                ('consecutive_code_verification_attempt_counter', models.PositiveSmallIntegerField()),
                ('user_auth', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='authapis.userauth')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
